<template>
  <div class="container px-0">
    <div :class="show ? 'fade-out-bottom' : ''">
      <button
        class="
          btn btn-raised btn-flat btn-block btn-lg btn-info
          text-polen
          mx-auto
          d-block
          px-4
        "
        @click="play"
      >
        Ver o(s) vencedor(es)!
      </button>
    </div>

    <div v-if="show" :class="show ? 'fade-in-bottom' : ''">
      <div class="font-monospace mb-5">
        <h2 class="mb-3">
          <span class="bg-info text-polen py-2 px-2">
            <strong class="marker-line"><em>Vencedor(es)</em></strong>
          </span>
        </h2>
        <img
          v-lazy="winner"
          class="img-fluid mx-auto d-block"
          :alt="winnerName"
          :title="winnerName"
        />
        <p class="text-info text-center my-3">
          <em>
            <a :href="winnerHD" class="text-polen mx-1" target="_blank">
              <span class="marker-line bg-info text-polen py-1">
                Clique aqui
              </span>
            </a>
            para baixar a versão em HD.
          </em>
        </p>
      </div>
      <div class="font-monospace mb-5">
        <h3 class="mb-3">
          <span class="bg-info text-polen py-2 px-2">
            <strong class="marker-line"><em> 2ª colocação </em></strong>
          </span>
        </h3>
        <p v-for="(second, i) in seconds" :key="i" class="text-info text-size">
          <em>"{{ second.quote }}" - {{ second.name }}</em>
        </p>
      </div>
      <div class="font-monospace mb-5">
        <h3 class="mb-3">
          <span class="bg-info text-polen py-2 px-2">
            <strong class="marker-line"><em> 3ª colocação </em></strong>
          </span>
        </h3>
        <p v-for="(third, i) in thirds" :key="i" class="text-info text-size">
          <em>"{{ third.quote }}" - {{ third.name }}</em>
        </p>
      </div>
      <div class="font-monospace mb-5">
        <h2 class="mb-3">
          <span class="bg-info text-polen py-2 px-2">
            <strong><em> Bônus </em></strong>
          </span>
        </h2>
        <h4 class="bg-info text-polen py-2 px-2 mb-3">
          <span class="">
            <strong><em> Daft Vitola - Wallpaper </em></strong>
          </span>
        </h4>
        <img
          v-lazy="daft"
          class="img-fluid mx-auto d-block"
          alt="Daft Vitola"
          title="Daft Vitola"
        />
        <p class="text-info text-center my-3">
          <em>
            <a :href="daftHD" class="text-polen mx-1" target="_blank">
              <span class="marker-line bg-info text-polen py-1">
                Clique aqui
              </span>
            </a>
            para baixar a versão em HD.
          </em>
        </p>
      </div>
    </div>
  </div>
</template>
<script>
import { Howl } from "howler";

import urna from "@/assets/audio/urna.mp3";

import dataSecond from "~/assets/data/seconds.json";
import dataThird from "~/assets/data/thirds.json";

export default {
  data() {
    return {
      sound: "",
      show: false,
      winnerName: "Ultimate",
      winner: "https://i.imgur.com/tjVBugA.jpg",
      winnerHD: "https://i.imgur.com/fKMl9XG.jpg",
      daft: "https://i.imgur.com/3ndugq6.jpg",
      daftHD: "https://i.imgur.com/bZQauq4.jpg",
      seconds: dataSecond,
      thirds: dataThird,
    };
  },
  mounted() {
    this.sound = new Howl({
      src: [urna],

      onloaderror(id, err) {
        // eslint-disable-next-line no-console
        console.warn("failed to load sound file:", { id, err });
      },
    });
  },
  methods: {
    play() {
      this.sound.play();
      setTimeout(() => (this.show = true), 300);
      clearTimeout();
    },

    showWinner() {},
  },
};
</script>
<style lang="scss">
.text-size {
  font-size: 18px;
}

.fade-in-bottom {
  -webkit-animation: fade-in-bottom 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) 2s
    both;
  animation: fade-in-bottom 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) 2s both;
}

.fade-out-bottom {
  -webkit-animation: fade-out-bottom 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    0.5s both;
  animation: fade-out-bottom 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.5s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-7-3 17:54:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

/**
 * ----------------------------------------
 * animation fade-out-bottom
 * ----------------------------------------
 */
@-webkit-keyframes fade-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
}
@keyframes fade-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
}
</style>
