<!-- eslint-disable vue/no-v-for-template-key -->
<template>
  <div class="container px-0">
    <div :class="show ? 'fade-out-bottom' : ''">
      <button
        class="
          btn btn-raised btn-flat btn-block btn-lg btn-pink
          text-polen
          mx-auto
          d-block
          px-4
        "
        @click="play"
      >
        Ver o(s) vencedor(es)!
      </button>
    </div>

    <div v-if="show" :class="show ? 'fade-in-bottom' : ''">
      <div class="mb-5">
        <h2 class="mb-3">
          <span class="bg-pink text-polen py-2 px-2">
            <strong class="marker-line">Vencedor(es)</strong>
          </span>
        </h2>
        <div v-for="(winner, i) in winners" :key="i">
          <img v-lazy="winner.winner" class="img-fluid mx-auto d-block" />
          <p class="text-pink text-center my-3">
            <strong>
              <a
                :href="winner.winnerHD"
                class="text-polen mx-1"
                target="_blank"
              >
                <span class="marker-line bg-pink text-polen py-1">
                  Clique aqui
                </span>
              </a>
              para baixar a versão em HD.
            </strong>
          </p>
        </div>
      </div>
      <div class="mb-5">
        <h3 class="mb-3">
          <span class="bg-pink text-polen py-2 px-2">
            <strong class="marker-line">2ª colocação </strong>
          </span>
        </h3>
        <p
          v-for="(second, i) in seconds"
          :key="i"
          class="text-pink text-size"
          style="font-weight: 500"
        >
          "{{ second.quote }}" - {{ second.name }}
        </p>
      </div>
      <div class="mb-5">
        <h3 class="mb-3">
          <span class="bg-pink text-polen py-2 px-2">
            <strong class="marker-line"> 3ª colocação</strong>
          </span>
        </h3>
        <p
          v-for="(third, i) in thirds"
          :key="i"
          class="text-pink text-size"
          style="font-weight: 500"
        >
          "{{ third.quote }}" - {{ third.name }}
        </p>
      </div>
      <div class="mb-5">
        <h2 class="mb-3">
          <span class="bg-pink text-polen py-2 px-2">
            <strong> Bônus </strong>
          </span>
        </h2>
        <h4 class="bg-pink text-polen py-2 px-2 mb-3">
          <span class="">
            <strong>Daft Vitola - Wallpaper </em></strong>
          </span>
        </h4>
        <img
          v-lazy="daft"
          class="img-fluid mx-auto d-block"
          alt="Daft Vitola"
          title="Daft Vitola"
        />
        <p class="text-pink text-center my-3">
          <strong>
            <a :href="daftHD" class="text-polen mx-1" target="_blank">
              <span class="marker-line bg-pink text-polen py-1">
                Clique aqui
              </span>
            </a>
            para baixar a versão em HD.
          </strong>
        </p>
      </div>
    </div>
  </div>
</template>
<script>
import { Howl } from "howler";

import urna from "@/assets/audio/urna.mp3";

import dataSecond from "~/assets/data/seconds.json";
import dataThird from "~/assets/data/thirds.json";

export default {
  data() {
    return {
      sound: "",
      show: false,
      winners: [
        {
          winner: "https://i.imgur.com/XIua835.jpg",
          winnerHD: "https://i.imgur.com/djmCr5e.jpg",
        },
        {
          winner: "https://i.imgur.com/5irOkhi.jpg",
          winnerHD: "https://i.imgur.com/Csrx4M5.jpg",
        },
        {
          winner: "https://i.imgur.com/lEm9eNK.jpg",
          winnerHD: "https://i.imgur.com/eHpB9xX.jpg",
        },
      ],

      daft: "https://i.imgur.com/3ndugq6.jpg",
      daftHD: "https://i.imgur.com/bZQauq4.jpg",
      seconds: dataSecond,
      thirds: dataThird,
    };
  },
  mounted() {
    this.sound = new Howl({
      src: [urna],

      onloaderror(id, err) {
        // eslint-disable-next-line no-console
        console.warn("failed to load sound file:", { id, err });
      },
    });
  },
  methods: {
    play() {
      this.sound.play();
      setTimeout(() => (this.show = true), 300);
      clearTimeout();
    },

    showWinner() {},
  },
};
</script>
<style lang="scss">
.text-size {
  font-size: 18px;
}

.btn {
  font-family: "Barlow", sans-serif;
}

.fade-in-bottom {
  -webkit-animation: fade-in-bottom 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) 2s
    both;
  animation: fade-in-bottom 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) 2s both;
}

.fade-out-bottom {
  -webkit-animation: fade-out-bottom 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    0.5s both;
  animation: fade-out-bottom 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.5s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-7-3 17:54:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more pink.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

/**
 * ----------------------------------------
 * animation fade-out-bottom
 * ----------------------------------------
 */
@-webkit-keyframes fade-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
}
@keyframes fade-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
}
</style>
