<template>
  <div class="bg-dark">
    <div
      class="container-fluid bg-polen background-texture"
      style="min-height: 100vh"
    >
      <div class="container py-5">
        <div class="">
          <h1 class="main-title header-name mb-3">
            <span
              class="
                background-texture
                marker-line
                bg-pink
                text-polen
                px-md-4
                py-md-3 py-2
                px-3
              "
            >
            </span>
          </h1>
          <p>
            <span
              class="marker-line bg-pink text-polen py-1"
              style="font-weight: 500"
            >
              Developed by Team Blklight
            </span>
          </p>
          <h2 class="mt-3 mb-4" style="font-weight: 700">
            <span class="marker-line bg-pink text-polen py-1 px-3">
              <strong> 2022/2</strong>
            </span>
          </h2>
        </div>
        <Winners />
        <AllTimeChampions />
      </div>
    </div>
  </div>
</template>

<script>
import { Howl } from "howler";

import urna from "~/assets/audio/urna.mp3";

import dataSecond from "~/assets/data/seconds.json";
import dataThird from "~/assets/data/thirds.json";
// import Winners from "~/components/Winners.vue";
export default {
  // components: { Winners },
  data() {
    return {
      sound: "",
      show: false,
      winnerName: "Ultimate",
      winner: "https://i.imgur.com/qb7PZXm.jpg",
      winnerHD: "https://i.imgur.com/cSRyYIx.jpg",
      daft: "https://i.imgur.com/3ndugq6.jpg",
      daftHD: "https://i.imgur.com/bZQauq4.jpg",
      seconds: dataSecond,
      thirds: dataThird,
      windowWidth: "",
      headers: "",
    };
  },
  created() {},
  mounted() {
    window.onresize = () => {
      this.windowWidth = window.innerWidth;
    };
    this.sound = new Howl({
      src: [urna],
      onloaderror(id, err) {
        // eslint-disable-next-line no-console
        console.warn("failed to load sound file:", { id, err });
      },
    });
  },
  methods: {
    play() {
      this.sound.play();
      setTimeout(() => (this.show = true), 300);
      clearTimeout();
    },
    showWinner() {},
    headerChanger() {
      const headerNameFull = "#ManOfTheMatch";
      const headerNameShort = "#MOTM";
      if (this.windowWidth < 768) {
        return headerNameShort;
      } else {
        return headerNameFull;
      }
    },
  },
};
</script>

<style lang="scss">
body {
  background-color: #121212;
  font-family: "Barlow", sans-serif;
}

h1,
h2,
h3,
h4,
h5,
h6 {
  font-family: "Barlow", sans-serif !important;
}

.main-title {
  font-weight: 900;
  font-size: 88px;
  font-family: "Barlow", sans-serif;
}
@media screen and (max-width: 992px) {
  .main-title {
    font-size: 64px;
  }
}
/* @media screen and (max-width: 768px) {
  .main-title {
    font-size: 56px;
  }
} */
/* @media screen and (max-width: 576px) {
  .main-title {
    font-size: 2.5rem;
  }
} */

.freebirdFormviewerViewCenteredContent {
  width: 100% !important;
  max-width: 100% !important;
  margin: 0 auto;
}

.text-size {
  font-size: 18px;
}

.fade-in-bottom {
  -webkit-animation: fade-in-bottom 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) 2s
    both;
  animation: fade-in-bottom 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) 2s both;
}

.fade-out-bottom {
  -webkit-animation: fade-out-bottom 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    0.5s both;
  animation: fade-out-bottom 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.5s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-7-3 17:54:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

/**
 * ----------------------------------------
 * animation fade-out-bottom
 * ----------------------------------------
 */
@-webkit-keyframes fade-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
}
@keyframes fade-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
}

.header-name {
  ::after {
    content: "#ManOfTheMatch";
  }
}

@media screen and (max-width: 768px) {
  .header-name {
    ::after {
      content: "#MOTM";
    }
  }
}
</style>
